-- Role: testadmin
-- DROP ROLE IF EXISTS testadmin;

CREATE ROLE testadmin WITH
  LOGIN
  SUPERUSER
  INHERIT
  CREATEDB
  CREATEROLE
  NOREPLICATION
  ENCRYPTED PASSWORD 'SCRAM-SHA-256$4096:VDE2rJBUfPhx0ROS8PnNZw==$14Dlsx2gWX9hqhJWQVA65GRnQwtYrc0fwVRibZXZIKc=:HfPUnJTxe6lKN/m0Hua0QOlEiWyojf/XS3acd2lbSPI=';