-- Role: testuser
-- DROP ROLE IF EXISTS testuser;

CREATE ROLE testuser WITH
  LOGIN
  NOSUPERUSER
  INHERIT
  NOCREATEDB
  NOCREATEROLE
  NOREPLICATION
  ENCRYPTED PASSWORD 'SCRAM-SHA-256$4096:BR6+a+U+Vn4iGeAHeJvxCA==$30Zk8183Oj9wlW8ST5vg2IPfx5Eg68+kJ+7U1Um/ekQ=:vgWjn8XWFFcYFNkhS2Azz0Ar3kyqnxO00+IAn7nKOeE=';