spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/bookstore_management_system_db
    username: testadmin
    password: testpassword
    driver-class-name: org.postgresql.Driver
    initialization-mode: always
    schema:
      - classpath:resource/db/migration/databaseDDL.sql
      - classpath:resource/db/migration/testadmin_roleDDL.sql
      - classpath:resource/db/migration/testuser_roleDDL.sql
      - classpath:resource/db/migration/tableDDL.sql
      - classpath:resource/db/migration/rowDDL.sql
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update  # or validate
      show-sql: true
  thymeleaf:
    enabled: true
    prefix: classpath:/frontend/public/static/
    suffix: .html
    cache: false # Set to false for development, true for production
server:
  port: 8081
logging:
  level:
    org.springframework: INFO
    com.example: DEBUG
security:
  user:
    name: user
    password: password
