# Database configuration
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/bookstore_management_system_db
    username: testadmin
    password: testpassword
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
      show-sql: true
  thymeleaf:
    enabled: true
    prefix: classpath:/frontend/public/static/
    suffix: .html
    cache: false # Set to false for development, true for production

# Server configuration
server:
  port: 8081

# Logging configuration
logging:
  level:
    org.springframework: INFO
    com.example: DEBUG

# Security configuration
security:
  user:
    name: user
    password: password

# External service configuration
# external-service:
#   url: http://example.com/api
#   api-key: YOUR_API_KEY

# Database initialization
datasource:
  initialization-mode: always
  schema:
    - classpath:resource/db/migration/databaseDDL.sql
    - classpath:resource/db/migration/testadmin_roleDDL.sql
    - classpath:resource/db/migration/testuser_roleDDL.sql
    - classpath:resource/db/migration/tableDDL.sql
    - classpath:resource/db/migration/rowDDL.sql
